runtime: nodejs18
service: crowdfunding-fe
instance_class: F2
automatic_scaling:
  min_instances: 1

env_variables:
  NEXT_PUBLIC_CROWDFUNDING_API: https://crowdfunding-api-dot-crowdfunding-380517.de.r.appspot.com/api/v1
  NEXT_PUBLIC_CONTRACT_ADDRESS_CF: 0x848b92662f67971cf92ce0214107bBDA90316cda
  NEXT_PUBLIC_CONTRACT_ADDRESS_LT: 0xB6434EE024892CBD8e3364048a259Ef779542475

handlers:
  - url: /.*
    secure: always
    script: auto
