export const examplelist = [
  {
    title: "Project 1",
    subtitle: "This is the subtitle",
    story: "This is the Projects story",
    startDate: "",
    endSate: "01/01/2023",
    id: "1234",
    fiatAmount: 5000,
    image:
      "https://www.shutterstock.com/image-photo/word-example-written-on-magnifying-260nw-1883859943.jpg",
    status: "active",
    goal: [{ token: "USD", amount: 0.865122 }],
    currentAmount: [{ token: "USD", amount: 0.30035 }],
    category: "Technology",
    owner: "user",
    statusHistory: [{ date: "", statis: "active", statusName: "active" }],
  },
  {
    title: "Project 2",
    subtitle: "This is the subtitle",
    story: "This is the Projects story",
    startDate: "",
    endSate: "01/01/2023",
    id: "12345",
    fiatAmount: 5000,
    image:
      "https://www.shutterstock.com/image-photo/word-example-written-on-magnifying-260nw-1883859943.jpg",
    status: "active",
    goal: [{ token: "USD", amount: 0.865122 }],
    currentAmount: [{ token: "USD", amount: 0.09035 }],
    category: "Technology",
    owner: "user",
    statusHistory: [{ date: "", statis: "active", statusName: "active" }],
  },
  {
    title: "Project 3",
    subtitle: "This is the subtitle",
    story: "This is the Projects story",
    startDate: "",
    endSate: "01/01/2023",
    id: "12346",
    fiatAmount: 5000,
    image:
      "https://www.shutterstock.com/image-photo/word-example-written-on-magnifying-260nw-1883859943.jpg",
    status: "active",
    goal: [{ token: "USD", amount: 0.865122 }],
    currentAmount: [{ token: "USD", amount: 0.34035 }],
    category: "Technology",
    owner: "user",
    statusHistory: [{ date: "", statis: "active", statusName: "active" }],
  },
  {
    title: "Project 4",
    subtitle: "This is the subtitle",
    story: "This is the Projects story",
    startDate: "",
    endSate: "01/01/2023",
    id: "12347",
    fiatAmount: 5000,
    image:
      "https://www.shutterstock.com/image-photo/word-example-written-on-magnifying-260nw-1883859943.jpg",
    status: "active",
    goal: [{ token: "USD", amount: 0.865122 }],
    currentAmount: [{ token: "USD", amount: 0.03035 }],
    category: "Technology",
    owner: "user",
    statusHistory: [{ date: "", statis: "active", statusName: "active" }],
  },
  {
    title: "Project 5",
    subtitle: "This is the subtitle",
    story: "This is the Projects story",
    startDate: "",
    endSate: "01/01/2023",
    id: "12348",
    fiatAmount: 5000,
    image:
      "https://www.shutterstock.com/image-photo/word-example-written-on-magnifying-260nw-1883859943.jpg",
    status: "active",
    goal: [{ token: "USD", amount: 0.865122 }],
    currentAmount: [{ token: "USD", amount: 0.70035 }],
    category: "Technology",
    owner: "user",
    statusHistory: [{ date: "", statis: "active", statusName: "active" }],
  },
  {
    title: "Project 6",
    subtitle: "This is the subtitle",
    story: "This is the Projects story",
    startDate: "",
    endSate: "01/01/2023",
    id: "12349",
    fiatAmount: 5000,
    image:
      "https://www.shutterstock.com/image-photo/word-example-written-on-magnifying-260nw-1883859943.jpg",
    status: "active",
    goal: [{ token: "USD", amount: 0.865122 }],
    currentAmount: [{ token: "USD", amount: 0.00035 }],
    category: "Technology",
    owner: "user",
    statusHistory: [{ date: "", statis: "active", statusName: "active" }],
  },
];

export const forumlist = [
  {
    image: "https://www.shutterstock.com/image-photo/word-example-written-on-magnifying-260nw-1883859943.jpg",
    username: 'Username',
    date: 'Tues 14 Feb | 8:02 am',
    title: 'Discussion title',
    content:
    'Lörem ipsum gädiv trivåmon har prening än kodådat makronat kvasin. Posttropi antina flexidaritet fan. Tirar preren fastän poligen fåning. Trespeligen nytipyrad ultrar, nydat att byn tills rekoring. Fåll nispepågisk...',
    replies: 2,
  },
  {
    image: "https://www.shutterstock.com/image-photo/word-example-written-on-magnifying-260nw-1883859943.jpg",
    username: 'Username',
    date: 'Tues 14 Feb | 8:02 am',
    title: 'Discussion title',
    content:
    'Lörem ipsum gädiv trivåmon har prening än kodådat makronat kvasin. Posttropi antina flexidaritet fan. Tirar preren fastän poligen fåning. Trespeligen nytipyrad ultrar, nydat att byn tills rekoring. Fåll nispepågisk...',
    replies: 2,
  },
  {
    image: "https://www.shutterstock.com/image-photo/word-example-written-on-magnifying-260nw-1883859943.jpg",
    username: 'Username',
    date: 'Tues 14 Feb | 8:02 am',
    title: 'Discussion title',
    content:
    'Lörem ipsum gädiv trivåmon har prening än kodådat makronat kvasin. Posttropi antina flexidaritet fan. Tirar preren fastän poligen fåning. Trespeligen nytipyrad ultrar, nydat att byn tills rekoring. Fåll nispepågisk...',
    replies: 2,
  },
];
