import Head from "next/head";
import Link from "next/link";

import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>CROWD FOUNDING</h1>

        <div className={styles.grid}>
          <Link href="/login">
            <div className={styles.card}>
              <h2>login &rarr;</h2>
            </div>
          </Link>

          <Link href="/signup">
            <div className={styles.card}>
              <h2>signup &rarr;</h2>
            </div>
          </Link>

          <Link href="/account">
            <div className={styles.card}>
              <h2>account &rarr;</h2>
            </div>
          </Link>

          <Link href="/create">
            <div className={styles.card}>
              <h2>create &rarr;</h2>
            </div>
          </Link>

          <Link href="/discover">
            <div className={styles.card}>
              <h2>discover &rarr;</h2>
            </div>
          </Link>

          <Link href="/projects">
            <div className={styles.card}>
              <h2>projects &rarr;</h2>
              <p>/[author]/[projectId]</p>
            </div>
          </Link>
        </div>
      </main>
    </div>
  );
}
