import Head from "next/head";
import Image from "next/image";
import { useEffect, useRef } from "react";
import { scrollElements } from "utils/scrollElements";
import { useQuery } from "@tanstack/react-query";

import { Header, CardSkeleton, Project } from "components";
import { fetchCampaigns } from "utils/fetch";
import { QUERIES } from "../constants";
import background from "assets/background.gif";
import add from "assets/icons/add.svg";

import {
  Main,
  TitleContainer,
  Title,
  LogoContainer,
  Grid,
  ButtonsContainer,
  Button,
  ProjectContainer,
} from "../styles/Home.module.js";

export default function Home() {
  const sliderRecently = useRef();
  const sliderArts = useRef();
  const skeletons = new Array(5).fill(null);

  const { data, isLoading, isError } = useQuery(
    [QUERIES.campaigns],
    fetchCampaigns
  );

  useEffect(() => {
    scrollElements(sliderRecently);
    scrollElements(sliderArts);
  }, []);

  return (
    <>
      <Head>
        <title>Crowdfunding</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <Header />

        <LogoContainer>
          <Image src={background} alt="Logo" fill />
        </LogoContainer>

        <TitleContainer>
          <Title>CROWD</Title>
          <Title>FUNDING</Title>
        </TitleContainer>

        <Grid>
          <ButtonsContainer>
            <Button href="/create">
              <Image height={15} width={15} src={add} alt="add icon" />
              New Project
            </Button>
          </ButtonsContainer>

          <ProjectContainer ref={sliderRecently}>
            {isLoading || isError
              ? skeletons.map((_, index) => <CardSkeleton key={index} />)
              : data.campaigns.map((campaign, index) => (
                  <Project project={campaign} key={index} />
                ))}
          </ProjectContainer>
        </Grid>
      </Main>
    </>
  );
}
